In [2]:
import pysindy

....importing local pysindy copy....


In [7]:
    # import numpy as np
    # from scipy.integrate import odeint
    # from pysindy import SINDy
    # from pysindy.optimizers import STLSQ
    # lorenz = lambda z,t : [10*(z[1] - z[0]),
    #                         z[0]*(28 - z[2]) - z[1],
    #                         z[0]*z[1] - 8/3*z[2]]
    # t = np.arange(0,2,.002)
    # x = odeint(lorenz, [-8,8,27], t)
    # opt = STLSQ(threshold=0.1, alpha=.5)
    # model = SINDy(optimizer=opt)
    # model.fit(x, t=t[1]-t[0])
    # model.print()

In [159]:
import sys
sys.path.insert(0,"/Users/manujayadharan/git_repos/pysindy")



import pysindy
import numpy as np
from scipy.integrate import odeint
from pysindy import SINDy
from pysindy.optimizers import STLSQ
from sklearn.metrics import mean_squared_error
lorenz = lambda z,t : [10*(z[1] - z[0]),
                        z[0]*(28 - z[2]) - z[1],
                        z[0]*z[1] - 8/3*z[2]]
t = np.arange(0,2,.002)
x = odeint(lorenz, [-8,8,27], t)
noise = 1
threshold = 0.2

rmse = mean_squared_error(x, np.zeros(x.shape), squared=False)
x = x + np.random.normal(0, noise*rmse / 100.0, x.shape)
opt = STLSQ(threshold=threshold, alpha=.5)
model = SINDy(optimizer=opt)
model.fit(x, t=t[1]-t[0])
print("STLSQ optimizer....")
model.print()


import pysindy as ps
opt_adam = ps.optimizers.adam_STLSQ(threshold=threshold, alpha=.5, mom_init_iter=1, mom_memory=0.1, use_mom=True, mom_inplace=True,)
model_2 = SINDy(opt_adam)
model_2.fit(x, t=t[1]-t[0])
print(" adam-STLSQ optimizer....")



model_2.print()

STLSQ optimizer....
(x0)' = -10.018 x0 + 10.030 x1
(x1)' = 28.072 x0 + -1.136 x1 + -0.996 x0 x2
(x2)' = 3.533 1 + 0.887 x0 + -0.479 x1 + -2.903 x2 + 0.998 x0 x1
 adam-STLSQ optimizer....
(x0)' = -10.018 x0 + 10.030 x1
(x1)' = 28.072 x0 + -1.136 x1 + -0.996 x0 x2
(x2)' = 0.962 x0 + -2.817 x2 + 0.961 x0 x1


In [127]:
mom_history = np.array(opt_adam.mom_history)
opt_history_adam  = np.array(opt_adam.history_)
opt_history_orig = np.array(opt.history_)

In [14]:
opt_history_orig[1] - opt_history[1]

array([[ 0.        , -0.08910723,  0.06154257,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 1.0896035 ,  0.16332667,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , -0.00351503,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ]])

In [12]:
opt_history[0]

array([[-9.64895569e-03, -1.00046478e+01,  1.00038374e+01,
         7.65369398e-04, -3.15852085e-05, -2.93120448e-05,
         1.73525249e-04, -4.87091503e-05, -1.05165499e-04,
        -1.60698340e-05],
       [ 2.26880766e-02,  2.79944495e+01, -9.93575835e-01,
        -3.40276264e-03,  3.26828868e-06,  1.06618345e-03,
        -1.00014295e+00, -6.94384821e-04, -1.22218320e-04,
         1.35248892e-04],
       [-8.19281886e-02, -7.79668615e-03,  1.14104022e-02,
        -2.65831213e+00,  6.78705151e-04,  1.00008079e+00,
         2.77464075e-04, -3.19445037e-04, -5.14789205e-04,
        -2.08940175e-04]])

In [5]:
mom_history

array([[[ 0.        , -9.78300458,  9.84825416,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ],
        [-1.0896035 , 27.59312918,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , -2.64817514,
          0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ]],

       [[ 0.        , -9.99861773,  9.99871428,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ],
        [40.35281685, -6.44990851,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ]],

       [[ 0.        , -9.99861773,  9.99871428, 

In [14]:
mom_arr = opt_history[1]

In [15]:
for ind in range(2,4):
    mom_arr = 0.9 * mom_arr + 0.1*opt_history[ind]
    print(mom_arr)

[[ 0.42182376 -9.88482832  9.91871652  0.          0.          0.
   0.          0.          0.          0.        ]
 [-0.66011401 27.77893223 -0.86523902  0.          0.          0.
  -0.99366825  0.          0.          0.        ]
 [-0.12055897  0.          0.         -2.65317526  0.          0.99991043
   0.          0.          0.          0.        ]]
[[ 0.37964138 -9.89625538  9.92675649  0.          0.          0.
   0.          0.          0.          0.        ]
 [-0.5941026  27.79942442 -0.87834928  0.          0.          0.
  -0.99425949  0.          0.          0.        ]
 [-0.10850308  0.          0.         -2.65450322  0.          0.99990956
   0.          0.          0.          0.        ]]


In [17]:
print(np.where(abs(mom_history) > 0.1, mom_history, 0.)[1:])

[[[ 0.42213436 -9.88482832  9.91871652  0.          0.
    0.          0.          0.          0.          0.        ]
  [-0.6587641  27.77893223 -0.86523902  0.          0.
    0.         -0.99366825  0.          0.          0.        ]
  [-0.12034068  0.          0.         -2.65317526  0.
    0.99991043  0.          0.          0.          0.        ]]

 [[ 0.37992092 -9.89625538  9.92675649  0.          0.
    0.          0.          0.          0.          0.        ]
  [-0.59288769 27.79942442 -0.87834928  0.          0.
    0.         -0.99425949  0.          0.          0.        ]
  [-0.10830661  0.          0.         -2.65450322  0.
    0.99990956  0.          0.          0.          0.        ]]]


In [18]:
opt_history[-2:]

array([[[ 0.        , -9.99927692,  9.99899463,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ],
        [ 0.        , 27.9812197 , -0.99643931,  0.        ,
          0.        ,  0.        , -0.99953274,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , -2.66654099,
          0.        ,  0.99990241,  0.        ,  0.        ,
          0.        ,  0.        ]],

       [[ 0.        , -9.99909897,  9.9991162 ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ],
        [ 0.        , 27.9838541 , -0.99634161,  0.        ,
          0.        ,  0.        , -0.99958066,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , -2.66645487,
          0.        ,  0.9999017 ,  0.        ,  0.        ,
          0.        ,  0.        ]]])